### ISSUE TITLE
imagemin-cli — update to v.3

### ISSUE THREAD

**Issue by revelt** [damonbauer/npm-build-boilerplate#12]
We're using
`"imagemin-cli": "^2.1.0",`
but v.3 is the latest: https://github.com/imagemin/imagemin-cli

It looks like there was a breaking change, `-o` flag is now required.
Double-check, but I think:
`"imagemin": "imagemin src/images dist/images -p",`
should be changed to:
`"imagemin": "imagemin src/images -o dist/images",`

I also removed `-p` as there's no plugins to override. Once I did that, everything started to work fine again after update.

**Comment by erikkrieg** [comment]
I tested this but needed to make a small change to the path to get it working. I ran `imagemin src/images/* -o dist/images` and all appeared well.

**Comment by damonbauer** [comment]
Updated in a8f96ee. Thanks @revelt @erikkrieg!

**Comment by revelt** [comment]
awesome!
