### ISSUE TITLE
integrate `stylelint` for linting css

### ISSUE THREAD

**Issue by alexander-akait** [damonbauer/npm-build-boilerplate#14]
https://github.com/stylelint/stylelint

**Comment by damonbauer** [comment]
@evilebottnawi - thanks for the suggestion! I have not used `stylelint` before. I'd welcome a pull request with this feature if you want to make one.

**Comment by theskillwithin** [comment]
+1  
but make sure it supports sass/scss with or without tabs.  I think I ran into trouble with tabs in .sass files.  prob something I will integrate when it works for me.

https://github.com/theskillwithin/hrtcup/blob/master/package.json

**Comment by damonbauer** [comment]
Closed in #23. Thanks for the suggestion @evilebottnawi & @theskillwithin
