### ISSUE TITLE
npm task for zip files

### ISSUE THREAD

**Issue by mario-areias** [damonbauer/npm-build-boilerplate#15]
Thanks for all these tips. I am trying to achieve something similar to zip (or gzip or tar) my artifacts. So far I've seen `zlib`, `node-tar` and `node-zip` to accomplish that. However, they are not one line of code which I could use in my package.json file.

Do you know how to do that in a simple manner?

**Comment by damonbauer** [comment]
@mario-areias - since npm scripts are just an alias for bash commands, you should be able to run `zip` in your terminal. Inside of an npm script, that would look something like: 

``` js
"archive": "zip -r output_filename input_directory"
```

More details: http://snipplr.com/view/36580/unix-zip-file-or-directory/

**Comment by mario-areias** [comment]
Thanks for replying back.  Unfortunately, that's exactly what I want to avoid. I would like a javascript solution rather than a terminal solution. What I am using now is something like

``` json
 "copy:artifacts": "node scripts/copy-artifacts.js" 
```

And then I use standard node libraries to zip inside the `copy-artifacts.js`. But thanks anyway. Feel free to close this.
