### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by leph83** [damonbauer/npm-build-boilerplate#16]
this doesn't seem to work on windows machines. I get an error on the uglify script when installing and the watch task for scss files also won't work

**Comment by damonbauer** [comment]
@leph83 - you might try looking at #13. It addresses an issue regarding Windows. I believe things like `mkdir -p` and `rm -rf` don't work on Windows, so you might have to find replacements for them, like https://github.com/substack/node-mkdirp and https://github.com/isaacs/rimraf.

Sorry it doesn't work out of the box, I don't have a Windows machine to test on :/

**Comment by leph83** [comment]
got it up and running by replacing single quotes with escaped double quotes \" and by adding rimraf and glob. Thanks a lot. I was very happy to find this repo cause I wanted to do the exact same thing but had lots of problems cause of...reasons.
