### ISSUE TITLE
onchange (osx)

### ISSUE THREAD

**Issue by theskillwithin** [damonbauer/npm-build-boilerplate#17]
on the npm build boilerplate I seem to be having issues with onchange,  when I test everything out separately that seems to be my issue.  onchange appears to run but then doesn't seem to notice when the file has changed? 

also.  will onchange run async/at the same time as browser sync?

I am also trying others like npm watch no luck yet.  ill let you know if I figure it out, after this I just have to setup my browsersync config and this solution will be ready for me! no more gulp!

**Comment by vitaligent** [comment]
I was having the same problem. I fixed it by changing the following code: 
`"watch:css": "onchange \"src/scss/\" -- npm run build:css",`
to
`"watch:css": "onchange \"src/scss/**\" -- npm run build:css",`

**Comment by theskillwithin** [comment]
Here is what I did

https://gist.github.com/theskillwithin/d3c57a5c93c2373ffa0ba3da7992a06a
