### ISSUE TITLE
HTML Compress

### ISSUE THREAD

**Issue by kuanhsuh** [damonbauer/npm-build-boilerplate#26]
how do you deal with compressing HTML with this boilerplate

**Comment by tpkahlon** [comment]
You can try a templating language to handle HTML files like Pug. See example: http://github.com/tpkahlon/npm-app.git.

**Comment by adamgian** [comment]
It's possible to do it in the command line using HTML-minifier (https://github.com/kangax/html-minifier) and therefore also possible with a npm script.

Example below with likely options/settings when using HTML-minifier:
```
html-minifier --input-dir html/ --output-dir html/ --file-ext html --collapse-whitespace --remove-comments --minify-js --minfy-css
```

**Comment by damonbauer** [comment]
@kuansuh, the comment above from @adamgian looks like a good solution.
