### ISSUE TITLE
Question: Whats the purpose of `|| true`

### ISSUE THREAD

**Issue by mischah** [damonbauer/npm-build-boilerplate#32]
Hej,

I wonder what this is about? 🤔 
https://github.com/damonbauer/npm-build-boilerplate/blob/1589c7a21692df5a8c1fa48df333fbdb3480402d/package.json#L24 

Cheers, Michael

**Comment by damonbauer** [comment]
This was added in #23. It's not completely necessary, so you should be able to remove it without issue.
