### ISSUE TITLE
Autoprefixer does not trigger -webkit- prefix.

### ISSUE THREAD

**Issue by tpkahlon** [damonbauer/npm-build-boilerplate#33]
Upon Sass compilation, generated CSS files are missing "webkit" prefix.

**Comment by damonbauer** [comment]
Are you sure the code being prefixed _needs_ `-webkit-`? The default configuration of autoprefixer is for the `last 2 versions` of a browser.

Unless there is an error running autoprefixer, this shouldn't be a bug; rather, it would be an autoprefixer configuration option you can add. It uses `browserslist` under the hood, so take a look at their documentation: https://github.com/ai/browserslist
