### ISSUE TITLE
Auto image minify

### ISSUE THREAD

**Issue by ghost** [damonbauer/npm-build-boilerplate#9]
Thanks for that,

Is there a way that while the scripts are running in the background, when we add new images to src/images/ that they will automatically be minified into dist/images/ ?
Or at least get automatically copied from src/images/ to dist/images/ until npm restart ?

Right now when all npm scripts are running, images copied to src/images/ are not minified/copied to dist/images/ so a restart is a must and that's time consuming.

**Comment by damonbauer** [comment]
@Arovane -

I added a script to watch the `src/images` directory. When an image is added, edited or deleted, the script will run the the `build:images` task.

[This is the relevant commit](https://github.com/damonbauer/npm-build-boilerplate/commit/7bfaa1339f87ac15aabddbb038e5f16a359c6b40).
